### 1-2.导入版本检查

In [1]:
import numpy as np
print(np.__version__)
np.show_config()

1.16.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


### 3.创建一个10维的向量

In [3]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4.数组占用内存的大小

In [5]:
z = np.zeros((10, 10))
print(f'{z.size * z.itemsize} bytes')

800 bytes


### 5.从命令行获取api的文档

In [7]:
! python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

### 6.创建大小为10，第5个元素为1的向量

In [8]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 7.创建一个从10到49的向量

In [9]:
z = np.arange(10, 50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8.反转向量

In [10]:
z = np.arange(50)
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### 9.创建一个0-8的3x3矩阵

In [13]:
nz = np.arange(9).reshape((3,3))
nz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10.从指定数组中找出非零元素的索引

In [14]:
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4]),)

### 11.创建3x3的单位向量

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 12.创建3x3x3的随机张量

In [16]:
np.random.random((3,3,3))

array([[[0.34282518, 0.16559371, 0.90485649],
        [0.78955623, 0.55603327, 0.18013773],
        [0.49660208, 0.63365203, 0.66846831]],

       [[0.88175637, 0.54336855, 0.6097875 ],
        [0.79651274, 0.18562408, 0.5893058 ],
        [0.04913705, 0.21157224, 0.77078224]],

       [[0.15794543, 0.46873215, 0.2405402 ],
        [0.46853508, 0.53329237, 0.07584   ],
        [0.83479012, 0.59437738, 0.48493679]]])

### 13.创建10x10随机张量，并找出最大值和最小值

In [21]:
s = np.random.random((10,10))
s, s.min(), s.max()

(array([[0.97865134, 0.36990256, 0.49410215, 0.40618375, 0.65704416,
         0.2208883 , 0.28048677, 0.53736338, 0.2331402 , 0.67412809],
        [0.37290618, 0.15140794, 0.56296107, 0.02344776, 0.8706872 ,
         0.00143751, 0.10568316, 0.68733361, 0.47629723, 0.37902334],
        [0.10106211, 0.1812896 , 0.19078727, 0.72177187, 0.84592366,
         0.80448102, 0.3668204 , 0.5347369 , 0.96256022, 0.88098586],
        [0.02960791, 0.39161832, 0.80217883, 0.8411179 , 0.70032741,
         0.64002788, 0.81521434, 0.41071292, 0.54183927, 0.31692161],
        [0.97321478, 0.98591688, 0.43029702, 0.52824672, 0.98596004,
         0.24321835, 0.36172837, 0.14590416, 0.81943029, 0.81348942],
        [0.84794683, 0.3782878 , 0.06172852, 0.11194601, 0.3371251 ,
         0.3375967 , 0.00361938, 0.34865985, 0.53373933, 0.54454313],
        [0.32141157, 0.05576695, 0.13828434, 0.83627648, 0.4217362 ,
         0.97803267, 0.79584   , 0.77256564, 0.67031951, 0.62464299],
        [0.07257423, 0.4802

### 14.创建随机大小为30的张量并获取均值

In [22]:
z = np.random.random(30)
z, z.mean()

(array([0.15710425, 0.15800184, 0.79166578, 0.45142916, 0.24873449,
        0.16842868, 0.55482157, 0.7940582 , 0.99546374, 0.91975086,
        0.04721699, 0.17479541, 0.58974601, 0.73565342, 0.99278368,
        0.53119133, 0.64556544, 0.64349445, 0.36830221, 0.60690088,
        0.15972224, 0.55968352, 0.13472359, 0.23037601, 0.56741765,
        0.29503977, 0.28678096, 0.09392781, 0.09047634, 0.59084744]),
 0.4528034563805088)

### 15.创建2维张量，1在外围，0在内围

In [23]:
s = np.ones((10, 10))
s[1:-1,1:-1] = 0
s

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 16.给指定的张量外围加一圈0

In [25]:
s = np.ones((5, 5))
s = np.pad(s, pad_width=1, mode='constant', constant_values=0)
s

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

### 17.下面的表达式输出是什么

In [27]:
test = [0 * np.nan, np.nan==np.nan, np.inf > np.nan, np.nan - np.nan, np.nan in set([np.nan]), 0.3 == 3 * 0.1]
test

[nan, False, False, nan, True, False]

### 18.创建5x5张量，并且对角线下元素为1,2,3,4

In [28]:
np.diag(1+np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### 19.创建8x8张量，且让其符合跳棋布局

In [29]:
s = np.zeros((8, 8), dtype=int)
s[1::2, ::2] = 1
s[::2, 1::2] = 1
s

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 20.一个维度为6x7x8的张量，其第100个元素的维度索引是多少

In [30]:
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

### 21.使用`tile`函数创建棋盘张量

In [31]:
np.tile(np.array([[0, 1],[1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 22.随机张量的正则化

In [33]:
s = np.random.random((5, 5))
s = (s - np.mean(s)) / (np.std(s))
s

array([[-0.88814082, -1.51537362,  0.29176951,  0.58308696,  0.15144328],
       [ 0.70494842,  1.20053038, -0.70039649,  0.39450527, -0.34266141],
       [ 0.64800266, -1.02017847,  0.8818805 ,  0.66726354,  1.44609547],
       [-1.61087948, -1.98087904, -1.73995106,  0.30925981,  0.40657171],
       [-0.9282712 ,  0.5920912 ,  1.13907418,  1.29341663,  0.01679206]])

### 23.创建一个将颜色描述为四个无符号字节的自定义dtype

In [34]:
color = np.dtype([
    ('r', np.ubyte, 1),
    ('g', np.ubyte, 1),
    ('b', np.ubyte, 1),
    ('a', np.ubyte, 1),
])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

### 24.张量的矩阵乘法

In [35]:
s1 = np.dot(np.ones((5, 3)), np.ones((3, 2)))
s1

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

### 25.给定1维向量，对值在3-8的元素取负

In [37]:
s = np.arange(11)
s[(3 < s) & (s <= 8)] *= -1
s

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

### 26.下面表达式的输出

In [38]:
sum(range(5), -1)

9

In [39]:
from numpy import *
sum(range(5), -1)

10

### 27.以下合法的表达式

In [40]:
s = np.arange(9).reshape((3,3))
s

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
s ** s

array([[       1,        1,        4],
       [      27,      256,     3125],
       [   46656,   823543, 16777216]])

In [42]:
2 << s >> 2

array([[  0,   1,   2],
       [  4,   8,  16],
       [ 32,  64, 128]])

In [43]:
s <- s

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [44]:
1j * s

array([[0.+0.j, 0.+1.j, 0.+2.j],
       [0.+3.j, 0.+4.j, 0.+5.j],
       [0.+6.j, 0.+7.j, 0.+8.j]])

In [45]:
s/1/1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [46]:
s<s>s

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### 28.以下表达式的结果

In [48]:
np.array(0) / np.array(0)

/home/ljh/anaconda3/envs/nlp_streamlit/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [49]:
np.array(0) // np.array(0)

/home/ljh/anaconda3/envs/nlp_streamlit/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [50]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

### 29.合理取整

In [52]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-6.75249955 -8.38820961  3.26681962  1.5390238   9.18848284 -5.97553043
  9.06095915  8.65087933  2.936704   -2.28259777]
[-7. -9.  4.  2. 10. -6. 10.  9.  3. -3.]


### 30.寻找两个张量的相同值

In [54]:
s1 = np.random.randint(0, 10, 10)
print(s1)
s2 = np.random.randint(0, 10, 10)
print(s2)

[6 9 9 0 8 4 4 4 6 3]
[8 7 4 9 0 9 3 0 0 9]


In [55]:
np.intersect1d(s1, s2)

array([0, 3, 4, 8, 9])

### 31.忽略numpy警告

In [4]:
defaults = np.seterr(all='ignore')

In [5]:
s = np.ones(1) / 0

In [6]:
s

array([inf])

In [7]:
np.seterr(**defaults)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [8]:
nz = np.nonzero([1,2,3,0,0,5,0])
nz

(array([0, 1, 2, 5]),)

### 32.表达式输出 - 复数

In [9]:
np.sqrt(-1) == np.emath.sqrt(-1)

/home/ljh/anaconda3/envs/nlp_streamlit/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [10]:
np.sqrt(-1)

/home/ljh/anaconda3/envs/nlp_streamlit/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


nan

In [11]:
np.emath.sqrt(-1)

1j

### 33.获取昨天，今天，明天的日期

In [12]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
yesterday, today, tomorrow

(numpy.datetime64('2020-03-31'),
 numpy.datetime64('2020-04-01'),
 numpy.datetime64('2020-04-02'))

### 34.获取2016年7月份所有的日期

In [13]:
s = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
s

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

### 35.**原地计算以下式子((A+B)*(-A/2))**

In [14]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

### 36.用5种方式从一个随机带小数的数组中抽取整数

In [16]:
Z = np.random.uniform(0,10,10)
print(Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[9.2363541  5.81770409 6.97628807 2.60160465 7.9521065  6.9025715
 9.81981787 8.82999143 6.07077572 5.03208172]
[9. 5. 6. 2. 7. 6. 9. 8. 6. 5.]
[9. 5. 6. 2. 7. 6. 9. 8. 6. 5.]
[9. 5. 6. 2. 7. 6. 9. 8. 6. 5.]
[9 5 6 2 7 6 9 8 6 5]
[9. 5. 6. 2. 7. 6. 9. 8. 6. 5.]


### 37.创建一个每行范围在0-5的5*5矩阵

In [18]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 38.使用生成器构建数组

In [19]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [21]:
np.fromiter((s for s in range(10)), dtype=float, count=3)

array([0., 1., 2.])

### 39.创建区间(0,1)的值

In [22]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [25]:
# endpoint，决定最后一个数是否为参数stop处的数
Z = np.linspace(0,1,11)[1:]
print(Z)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### 40.创建一个随机向量并排序

In [26]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.13602845 0.17446344 0.25352851 0.41665601 0.44897837 0.61457149
 0.6159659  0.67000031 0.67249238 0.87723055]


### 41.对一个小型数组进行求和，使其求和速度快于内建函数np.sum()

In [30]:
%%timeit
Z = np.arange(10)
np.add.reduce(Z)

1.37 µs ± 12.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [31]:
%%timeit
Z = np.arange(10)
np.sum(Z)

2.89 µs ± 61.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### 42.验证两个随机数组是否相等

In [32]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[1 0 1 1 1]
[1 1 1 0 0]
False
False


### 43.让一个数组无法被更改

In [33]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

### 44.将一个10*2的笛卡尔坐标转换成极坐标

In [34]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.37447246 0.95189727 1.05162407 1.19085834 0.66473055 0.98800233
 0.84394419 1.16626468 0.59135395 1.21044533]
[0.67643607 0.02033565 0.38281584 0.93870108 1.34584781 0.79236102
 0.69694668 0.97271225 1.1574381  0.63746085]


### 45.将数组中的最大值替换成0

In [35]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.5643563  0.38674909 0.92087286 0.64238493 0.0909707  0.23189555
 0.33152668 0.45225558 0.09469719 0.57088053]
[0.5643563  0.38674909 0.         0.64238493 0.0909707  0.23189555
 0.33152668 0.45225558 0.09469719 0.57088053]


### 46.创建一个覆盖（0,1）（0,1）的坐标

In [36]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


### 47.根据给出的数组X，Y创建柯西矩阵(Cij =1/(xi - yj))

In [37]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


### 48.打印numpy中支持的数据类型的极值

In [39]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
print('-' * 20)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
--------------------
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


### 49.打印出数组的所有值（不省略很长的小数点）

In [45]:
import sys
np.set_printoptions(threshold=sys.maxsize)
Z = np.random.random((3,3))
print(Z)

[[0.84691369 0.04446819 0.10389416]
 [0.06886288 0.38702204 0.95577576]
 [0.02039421 0.25933737 0.67765023]]


### 50.找出数组中最接近给定值的值

In [47]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin()
print(Z[index])

40.30718012402842
40


### 51.创建结构数组来表示位置和颜色

In [48]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


### 52.

### 53.

### 54.

### 55.

### 56.

### 57.

### 58.

### 59.

### 60.

### 61.

### 62.

### 63.

### 64.

### 65.

### 66.

### 67.

### 68.

### 69.

### 70.

### 71.

### 72.

### 73.

### 74.

### 75.

### 76.

### 77.

### 78.

### 79.

### 80.

### 81.

### 82.

### 83.

### 84.

### 85.

### 86.

### 87.

### 88.

### 89.

### 90.

### 91.

### 92.

### 99.

### 94.

### 95.

### 96.

### 97.

### 98.

### 100.